EXNO: '005'
method_fillna: '-999'  # '-999' or 'forward'
option: 
  small: true
  train: true
  predict: true

defaults:
  - cvStrategy: nocv  # 'nocv' or 'PurgedGroupTimeSeriesSplit'
  - model: XGBClassifier
