name: lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    env: 
      DOCKER_BUILDKIT: 1
    container:
      image: gcr.io/kaggle-images/python@sha256:993897c5431c85530f48a9fe6546d01decc42d91ab05f4d9eb31ab0da835fe90

    steps:
      - uses: actions/checkout@v2
      - run: make install
      - run: make lint
